name: shop
channels:
  - conda-forge
dependencies:
  - python=3.11
  - flask
  - sqlalchemy
  - python-dotenv
  - pip
  - pip:
    - Flask-Login==0.6.3
    - bcrypt==4.2.0
    - stripe==10.5.0
    - requests==2.32.3
